from typing import Dict, Any, Tuple

class ToolValidator:
    """
    Sits between the Slow Reasoner and the Tool Manager.
    Verifies the LLM's tool call against the ingested schema.
    If a mistake is found, it generates a strict format error for the Reasoner to self-correct.
    """
    def __init__(self, reasoner_schema: Dict[str, Any]):
        # This is the formatted schema generated by ManifestIngestor
        self.schema = reasoner_schema

    def validate(self, tool_call: Dict[str, Any]) -> Tuple[bool, str]:
        """
        Validates the raw tool call.
        Returns (is_valid, error_message).
        If False, the Reasoner must correct and re-emit.
        If True, the Reasoner passes it to the ToolManager.
        """
        tool_name = tool_call.get("name")
        if not tool_name:
            return False, "Missing tool 'name' field. Expected format: {'name': '<tool_name>', 'slots': {...}}"
            
        valid_tools = self._get_valid_tool_names()
        if tool_name not in valid_tools:
            return False, f"Tool '{tool_name}' does not exist. Valid tools: {valid_tools}"
            
        # Additional deep format validation (slots, types) would go here based on self.schema
            
        return True, ""

    def _get_valid_tool_names(self) -> list:
        names = [t.get("name") for t in self.schema.get("read_only", [])]
        for t in self.schema.get("state_modifying", []):
            names.append(t.get("name"))
            # BUG FIX #8: ManifestIngestor generates an inverse tool (e.g. undo_book_flight)
            # for every state-modifying tool, and the Reasoner's instructions explicitly tell
            # it to call that inverse when undoing an action. But the inverse tool was never
            # registered here, so every undo call was rejected by the validator with
            # "tool does not exist". Include the inverse name when one is defined.
            inverse = t.get("inverse_tool", {})
            inverse_name = inverse.get("name")
            if inverse_name:
                names.append(inverse_name)
        return names
